### ISSUE TITLE
resource_already_exists_exception on first pass / ABI scan

### ISSUE THREAD

**Issue by robrigo** [eosrio/hyperion-history-api#33] opened 2020-04-25 21:43 UTC
I get the following issue when attempting to start the Hyperion indexer configured for Proton mainnet:

```
2020-04-25T21:24:13: [00_master] --------- Hyperion Indexer 3.0.0 ---------
2020-04-25T21:24:13: [00_master] Using parser version 1.8
2020-04-25T21:24:13: [00_master] Chain: proton
2020-04-25T21:24:13: [00_master]
2020-04-25T21:24:13: -------------------
2020-04-25T21:24:13:  ABI SCAN MODE
2020-04-25T21:24:13: -------------------
2020-04-25T21:24:13: [00_master] Purging all proton queues!
2020-04-25T21:24:13: [00_master] Elasticsearch: 7.6.2 | Lucene: 8.4.0
2020-04-25T21:24:13: [00_master] Ingest client ready at http://127.0.0.1:9200/
2020-04-25T21:24:13: [00_master] Painless Update Script loaded!
2020-04-25T21:24:13: [00_master] Mapping added for @voteproducer
2020-04-25T21:24:13: [00_master] Updating index templates for proton...
2020-04-25T21:24:15: [00_master] 12 index templates updated
2020-04-25T21:24:15: [00_master] Creating index proton-action-v1-000001...
2020-04-25T21:24:45: ResponseError: resource_already_exists_exception
2020-04-25T21:24:45:     at IncomingMessage.<anonymous> (/opt/eosio/src/Hyperion-History-API/node_modules/@elastic/elasticsearch/lib/Transport.js:296:25)
2020-04-25T21:24:45:     at IncomingMessage.emit (events.js:327:22)
2020-04-25T21:24:45:     at endReadableNT (_stream_readable.js:1201:12)
2020-04-25T21:24:45:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2020-04-25T21:24:45:   meta: {
2020-04-25T21:24:45:     body: { error: [Object], status: 400 },
2020-04-25T21:24:45:     statusCode: 400,
2020-04-25T21:24:45:     headers: {
2020-04-25T21:24:45:       'content-type': 'application/json; charset=UTF-8',
2020-04-25T21:24:45:       'content-length': '433'
2020-04-25T21:24:45:     },
2020-04-25T21:24:45:     warnings: null,
2020-04-25T21:24:45:     meta: {
2020-04-25T21:24:45:       context: null,
2020-04-25T21:24:45:       request: [Object],
2020-04-25T21:24:45:       name: 'elasticsearch-js',
2020-04-25T21:24:45:       connection: [Object],
2020-04-25T21:24:45:       attempts: 1,
2020-04-25T21:24:45:       aborted: false
2020-04-25T21:24:45:     }
2020-04-25T21:24:45:   }
2020-04-25T21:24:45: }
```

My Hyperion configs are below:

chains/proton.config.json

```
{
  "api": {
    "chain_name": "proton",
    "server_addr": "127.0.0.1",
    "server_port":  7000,
    "server_name": "127.0.0.1:7000",
    "provider_name": "EOS Detroit",
    "provider_url": "https://eosdetroit.io",
    "chain_logo_url": "https://bloks.io/img/chains/proton.png",
    "enable_caching": true,
    "cache_life": 1,
    "limits": {
      "get_actions": 1000,
      "get_voters": 100,
      "get_links": 1000,
      "get_deltas": 1000
    },
    "access_log": false,
    "enable_explorer": false
  },
  "settings": {
    "preview": false,
    "chain": "proton",
    "eosio_alias": "eosio",
    "parser": "1.8",
    "auto_stop": 300,
    "index_version": "v1",
    "debug": false,
    "rate_monitoring": true,
    "bp_logs": false,
    "bp_monitoring": false,
    "ipc_debug_rate": 60000,
    "allow_custom_abi": false
  },
  "blacklists": {
    "actions": [],
    "deltas": []
  },
  "whitelists": {
    "actions": [],
    "deltas": []
  },
  "scaling": {
    "batch_size": 10000,
    "queue_limit": 50000,
    "readers": 1,
    "ds_queues": 1,
    "ds_threads": 1,
    "ds_pool_size": 1,
    "indexing_queues": 1,
    "ad_idx_queues": 1,
    "max_autoscale": 4,
    "auto_scale_trigger": 20000
  },
  "indexer": {
    "start_on": 0,
    "stop_on": 0,
    "rewrite": false,
    "purge_queues": true,
    "live_reader": false,
    "live_only_mode": false,
    "abi_scan_mode": true,
    "fetch_block": true,
    "fetch_traces": true,
    "disable_reading": false,
    "disable_indexing": false,
    "process_deltas": true,
    "max_inline": 20
  },
  "features": {
    "streaming": {
      "enable": false,
      "traces": false,
      "deltas": false
    },
    "tables": {
      "proposals": true,
      "accounts": true,
      "voters": true,
      "userres": false,
      "delband": false
    },
    "index_deltas": true,
    "index_transfer_memo": true,
    "index_all_deltas": true
  },
  "prefetch": {
    "read": 50,
    "block": 100,
    "index": 500
  }
}
```

ecosystem.config.js
```
const {addApiServer, addIndexer} = require("./definitions/ecosystem_settings");

module.exports = {
    apps: [
        addIndexer('proton'), // Index chain name
        addApiServer('proton', 4) // API chain name, API threads number
    ]
};
```

connections.json
```
{
  "amqp": {
    "host": "127.0.0.1:5672",
    "api": "127.0.0.1:15672",
    "user": "admin",
    "pass": "[REDACTED]",
    "vhost": "hyperion"
  },
  "elasticsearch": {
    "host": "127.0.0.1:9200",
    "ingest_nodes": ["127.0.0.1:9200"],
    "user": "elastic",
    "pass": "[REDACTED]
  },
  "redis": {
    "host": "127.0.0.1",
    "port": "6379"
  },
  "chains": {
    "proton": {
      "name": "proton prod",
      "chain_id": "384da888112027f0321850a169f737c33e53b388aad48b5adace4bab97f437e0",
      "http": "http://127.0.0.1:8282",
      "ship": "ws://127.0.0.1:8887"
    }
  }
}
```

**Comment by igorls** [comment] 2020-05-30 19:48
@robrigo can you check if this is fixed on the latest master build ? A lot has changed since then and we weren't able to reproduce this issue

**Comment by robrigo** [comment] 2020-05-30 19:59
Can do Igor - will put this on the list to look into again this week. I got side tracked but do want to get this figured out soon. )

**Comment by robrigo** [comment] 2020-08-05 00:41
My team looked into this some more and we realized it had to do with using the Ansible Galaxy ES package - installing ES a different way didn't reproduce the issue.

**Comment by igorls** [comment] 2020-08-27 10:33
Good to know, I will be closing this then

**Closed by igorls** 2020-08-27 10:33 UTC
